name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.3

      - name: Install tools
        run: pip install -r requirements.txt
          
      - name: Test webpages
        run: python -m unittest discover tests
